// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type ActivationFunctionType = int8
const (
	ActivationFunctionTypeNONE ActivationFunctionType = 0
	ActivationFunctionTypeRELU ActivationFunctionType = 1
	ActivationFunctionTypeRELU_N1_TO_1 ActivationFunctionType = 2
	ActivationFunctionTypeRELU6 ActivationFunctionType = 3
	ActivationFunctionTypeTANH ActivationFunctionType = 4
	ActivationFunctionTypeSIGN_BIT ActivationFunctionType = 5
)

var EnumNamesActivationFunctionType = map[ActivationFunctionType]string{
	ActivationFunctionTypeNONE:"NONE",
	ActivationFunctionTypeRELU:"RELU",
	ActivationFunctionTypeRELU_N1_TO_1:"RELU_N1_TO_1",
	ActivationFunctionTypeRELU6:"RELU6",
	ActivationFunctionTypeTANH:"TANH",
	ActivationFunctionTypeSIGN_BIT:"SIGN_BIT",
}

