// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ArgMaxOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsArgMaxOptions(buf []byte, offset flatbuffers.UOffsetT) *ArgMaxOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ArgMaxOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ArgMaxOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ArgMaxOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ArgMaxOptions) OutputType() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ArgMaxOptions) MutateOutputType(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func ArgMaxOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ArgMaxOptionsAddOutputType(builder *flatbuffers.Builder, outputType int8) {
	builder.PrependInt8Slot(0, outputType, 0)
}
func ArgMaxOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
