// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type BuiltinOperator = int8
const (
	BuiltinOperatorADD BuiltinOperator = 0
	BuiltinOperatorAVERAGE_POOL_2D BuiltinOperator = 1
	BuiltinOperatorCONCATENATION BuiltinOperator = 2
	BuiltinOperatorCONV_2D BuiltinOperator = 3
	BuiltinOperatorDEPTHWISE_CONV_2D BuiltinOperator = 4
	BuiltinOperatorDEPTH_TO_SPACE BuiltinOperator = 5
	BuiltinOperatorDEQUANTIZE BuiltinOperator = 6
	BuiltinOperatorEMBEDDING_LOOKUP BuiltinOperator = 7
	BuiltinOperatorFLOOR BuiltinOperator = 8
	BuiltinOperatorFULLY_CONNECTED BuiltinOperator = 9
	BuiltinOperatorHASHTABLE_LOOKUP BuiltinOperator = 10
	BuiltinOperatorL2_NORMALIZATION BuiltinOperator = 11
	BuiltinOperatorL2_POOL_2D BuiltinOperator = 12
	BuiltinOperatorLOCAL_RESPONSE_NORMALIZATION BuiltinOperator = 13
	BuiltinOperatorLOGISTIC BuiltinOperator = 14
	BuiltinOperatorLSH_PROJECTION BuiltinOperator = 15
	BuiltinOperatorLSTM BuiltinOperator = 16
	BuiltinOperatorMAX_POOL_2D BuiltinOperator = 17
	BuiltinOperatorMUL BuiltinOperator = 18
	BuiltinOperatorRELU BuiltinOperator = 19
	BuiltinOperatorRELU_N1_TO_1 BuiltinOperator = 20
	BuiltinOperatorRELU6 BuiltinOperator = 21
	BuiltinOperatorRESHAPE BuiltinOperator = 22
	BuiltinOperatorRESIZE_BILINEAR BuiltinOperator = 23
	BuiltinOperatorRNN BuiltinOperator = 24
	BuiltinOperatorSOFTMAX BuiltinOperator = 25
	BuiltinOperatorSPACE_TO_DEPTH BuiltinOperator = 26
	BuiltinOperatorSVDF BuiltinOperator = 27
	BuiltinOperatorTANH BuiltinOperator = 28
	BuiltinOperatorCONCAT_EMBEDDINGS BuiltinOperator = 29
	BuiltinOperatorSKIP_GRAM BuiltinOperator = 30
	BuiltinOperatorCALL BuiltinOperator = 31
	BuiltinOperatorCUSTOM BuiltinOperator = 32
	BuiltinOperatorEMBEDDING_LOOKUP_SPARSE BuiltinOperator = 33
	BuiltinOperatorPAD BuiltinOperator = 34
	BuiltinOperatorUNIDIRECTIONAL_SEQUENCE_RNN BuiltinOperator = 35
	BuiltinOperatorGATHER BuiltinOperator = 36
	BuiltinOperatorBATCH_TO_SPACE_ND BuiltinOperator = 37
	BuiltinOperatorSPACE_TO_BATCH_ND BuiltinOperator = 38
	BuiltinOperatorTRANSPOSE BuiltinOperator = 39
	BuiltinOperatorMEAN BuiltinOperator = 40
	BuiltinOperatorSUB BuiltinOperator = 41
	BuiltinOperatorDIV BuiltinOperator = 42
	BuiltinOperatorSQUEEZE BuiltinOperator = 43
	BuiltinOperatorUNIDIRECTIONAL_SEQUENCE_LSTM BuiltinOperator = 44
	BuiltinOperatorSTRIDED_SLICE BuiltinOperator = 45
	BuiltinOperatorBIDIRECTIONAL_SEQUENCE_RNN BuiltinOperator = 46
	BuiltinOperatorEXP BuiltinOperator = 47
	BuiltinOperatorTOPK_V2 BuiltinOperator = 48
	BuiltinOperatorSPLIT BuiltinOperator = 49
	BuiltinOperatorLOG_SOFTMAX BuiltinOperator = 50
	BuiltinOperatorDELEGATE BuiltinOperator = 51
	BuiltinOperatorBIDIRECTIONAL_SEQUENCE_LSTM BuiltinOperator = 52
	BuiltinOperatorCAST BuiltinOperator = 53
	BuiltinOperatorPRELU BuiltinOperator = 54
	BuiltinOperatorMAXIMUM BuiltinOperator = 55
	BuiltinOperatorARG_MAX BuiltinOperator = 56
	BuiltinOperatorMINIMUM BuiltinOperator = 57
	BuiltinOperatorLESS BuiltinOperator = 58
	BuiltinOperatorNEG BuiltinOperator = 59
	BuiltinOperatorPADV2 BuiltinOperator = 60
	BuiltinOperatorGREATER BuiltinOperator = 61
	BuiltinOperatorGREATER_EQUAL BuiltinOperator = 62
	BuiltinOperatorLESS_EQUAL BuiltinOperator = 63
	BuiltinOperatorSELECT BuiltinOperator = 64
	BuiltinOperatorSLICE BuiltinOperator = 65
	BuiltinOperatorSIN BuiltinOperator = 66
	BuiltinOperatorTRANSPOSE_CONV BuiltinOperator = 67
	BuiltinOperatorSPARSE_TO_DENSE BuiltinOperator = 68
	BuiltinOperatorTILE BuiltinOperator = 69
	BuiltinOperatorEXPAND_DIMS BuiltinOperator = 70
	BuiltinOperatorEQUAL BuiltinOperator = 71
	BuiltinOperatorNOT_EQUAL BuiltinOperator = 72
	BuiltinOperatorLOG BuiltinOperator = 73
	BuiltinOperatorSUM BuiltinOperator = 74
	BuiltinOperatorSQRT BuiltinOperator = 75
	BuiltinOperatorRSQRT BuiltinOperator = 76
	BuiltinOperatorSHAPE BuiltinOperator = 77
	BuiltinOperatorPOW BuiltinOperator = 78
	BuiltinOperatorARG_MIN BuiltinOperator = 79
	BuiltinOperatorFAKE_QUANT BuiltinOperator = 80
	BuiltinOperatorREDUCE_PROD BuiltinOperator = 81
	BuiltinOperatorREDUCE_MAX BuiltinOperator = 82
	BuiltinOperatorPACK BuiltinOperator = 83
	BuiltinOperatorLOGICAL_OR BuiltinOperator = 84
	BuiltinOperatorONE_HOT BuiltinOperator = 85
	BuiltinOperatorLOGICAL_AND BuiltinOperator = 86
	BuiltinOperatorLOGICAL_NOT BuiltinOperator = 87
	BuiltinOperatorUNPACK BuiltinOperator = 88
	BuiltinOperatorREDUCE_MIN BuiltinOperator = 89
	BuiltinOperatorFLOOR_DIV BuiltinOperator = 90
	BuiltinOperatorREDUCE_ANY BuiltinOperator = 91
	BuiltinOperatorSQUARE BuiltinOperator = 92
	BuiltinOperatorZEROS_LIKE BuiltinOperator = 93
	BuiltinOperatorFILL BuiltinOperator = 94
	BuiltinOperatorFLOOR_MOD BuiltinOperator = 95
	BuiltinOperatorRANGE BuiltinOperator = 96
	BuiltinOperatorRESIZE_NEAREST_NEIGHBOR BuiltinOperator = 97
	BuiltinOperatorLEAKY_RELU BuiltinOperator = 98
	BuiltinOperatorSQUARED_DIFFERENCE BuiltinOperator = 99
	BuiltinOperatorMIRROR_PAD BuiltinOperator = 100
	BuiltinOperatorABS BuiltinOperator = 101
	BuiltinOperatorSPLIT_V BuiltinOperator = 102
	BuiltinOperatorUNIQUE BuiltinOperator = 103
	BuiltinOperatorCEIL BuiltinOperator = 104
	BuiltinOperatorREVERSE_V2 BuiltinOperator = 105
	BuiltinOperatorADD_N BuiltinOperator = 106
	BuiltinOperatorGATHER_ND BuiltinOperator = 107
	BuiltinOperatorCOS BuiltinOperator = 108
	BuiltinOperatorWHERE BuiltinOperator = 109
	BuiltinOperatorRANK BuiltinOperator = 110
	BuiltinOperatorELU BuiltinOperator = 111
	BuiltinOperatorREVERSE_SEQUENCE BuiltinOperator = 112
	BuiltinOperatorMATRIX_DIAG BuiltinOperator = 113
	BuiltinOperatorQUANTIZE BuiltinOperator = 114
	BuiltinOperatorMATRIX_SET_DIAG BuiltinOperator = 115
	BuiltinOperatorROUND BuiltinOperator = 116
	BuiltinOperatorHARD_SWISH BuiltinOperator = 117
	BuiltinOperatorIF BuiltinOperator = 118
	BuiltinOperatorWHILE BuiltinOperator = 119
	BuiltinOperatorNON_MAX_SUPPRESSION_V4 BuiltinOperator = 120
	BuiltinOperatorNON_MAX_SUPPRESSION_V5 BuiltinOperator = 121
)

var EnumNamesBuiltinOperator = map[BuiltinOperator]string{
	BuiltinOperatorADD:"ADD",
	BuiltinOperatorAVERAGE_POOL_2D:"AVERAGE_POOL_2D",
	BuiltinOperatorCONCATENATION:"CONCATENATION",
	BuiltinOperatorCONV_2D:"CONV_2D",
	BuiltinOperatorDEPTHWISE_CONV_2D:"DEPTHWISE_CONV_2D",
	BuiltinOperatorDEPTH_TO_SPACE:"DEPTH_TO_SPACE",
	BuiltinOperatorDEQUANTIZE:"DEQUANTIZE",
	BuiltinOperatorEMBEDDING_LOOKUP:"EMBEDDING_LOOKUP",
	BuiltinOperatorFLOOR:"FLOOR",
	BuiltinOperatorFULLY_CONNECTED:"FULLY_CONNECTED",
	BuiltinOperatorHASHTABLE_LOOKUP:"HASHTABLE_LOOKUP",
	BuiltinOperatorL2_NORMALIZATION:"L2_NORMALIZATION",
	BuiltinOperatorL2_POOL_2D:"L2_POOL_2D",
	BuiltinOperatorLOCAL_RESPONSE_NORMALIZATION:"LOCAL_RESPONSE_NORMALIZATION",
	BuiltinOperatorLOGISTIC:"LOGISTIC",
	BuiltinOperatorLSH_PROJECTION:"LSH_PROJECTION",
	BuiltinOperatorLSTM:"LSTM",
	BuiltinOperatorMAX_POOL_2D:"MAX_POOL_2D",
	BuiltinOperatorMUL:"MUL",
	BuiltinOperatorRELU:"RELU",
	BuiltinOperatorRELU_N1_TO_1:"RELU_N1_TO_1",
	BuiltinOperatorRELU6:"RELU6",
	BuiltinOperatorRESHAPE:"RESHAPE",
	BuiltinOperatorRESIZE_BILINEAR:"RESIZE_BILINEAR",
	BuiltinOperatorRNN:"RNN",
	BuiltinOperatorSOFTMAX:"SOFTMAX",
	BuiltinOperatorSPACE_TO_DEPTH:"SPACE_TO_DEPTH",
	BuiltinOperatorSVDF:"SVDF",
	BuiltinOperatorTANH:"TANH",
	BuiltinOperatorCONCAT_EMBEDDINGS:"CONCAT_EMBEDDINGS",
	BuiltinOperatorSKIP_GRAM:"SKIP_GRAM",
	BuiltinOperatorCALL:"CALL",
	BuiltinOperatorCUSTOM:"CUSTOM",
	BuiltinOperatorEMBEDDING_LOOKUP_SPARSE:"EMBEDDING_LOOKUP_SPARSE",
	BuiltinOperatorPAD:"PAD",
	BuiltinOperatorUNIDIRECTIONAL_SEQUENCE_RNN:"UNIDIRECTIONAL_SEQUENCE_RNN",
	BuiltinOperatorGATHER:"GATHER",
	BuiltinOperatorBATCH_TO_SPACE_ND:"BATCH_TO_SPACE_ND",
	BuiltinOperatorSPACE_TO_BATCH_ND:"SPACE_TO_BATCH_ND",
	BuiltinOperatorTRANSPOSE:"TRANSPOSE",
	BuiltinOperatorMEAN:"MEAN",
	BuiltinOperatorSUB:"SUB",
	BuiltinOperatorDIV:"DIV",
	BuiltinOperatorSQUEEZE:"SQUEEZE",
	BuiltinOperatorUNIDIRECTIONAL_SEQUENCE_LSTM:"UNIDIRECTIONAL_SEQUENCE_LSTM",
	BuiltinOperatorSTRIDED_SLICE:"STRIDED_SLICE",
	BuiltinOperatorBIDIRECTIONAL_SEQUENCE_RNN:"BIDIRECTIONAL_SEQUENCE_RNN",
	BuiltinOperatorEXP:"EXP",
	BuiltinOperatorTOPK_V2:"TOPK_V2",
	BuiltinOperatorSPLIT:"SPLIT",
	BuiltinOperatorLOG_SOFTMAX:"LOG_SOFTMAX",
	BuiltinOperatorDELEGATE:"DELEGATE",
	BuiltinOperatorBIDIRECTIONAL_SEQUENCE_LSTM:"BIDIRECTIONAL_SEQUENCE_LSTM",
	BuiltinOperatorCAST:"CAST",
	BuiltinOperatorPRELU:"PRELU",
	BuiltinOperatorMAXIMUM:"MAXIMUM",
	BuiltinOperatorARG_MAX:"ARG_MAX",
	BuiltinOperatorMINIMUM:"MINIMUM",
	BuiltinOperatorLESS:"LESS",
	BuiltinOperatorNEG:"NEG",
	BuiltinOperatorPADV2:"PADV2",
	BuiltinOperatorGREATER:"GREATER",
	BuiltinOperatorGREATER_EQUAL:"GREATER_EQUAL",
	BuiltinOperatorLESS_EQUAL:"LESS_EQUAL",
	BuiltinOperatorSELECT:"SELECT",
	BuiltinOperatorSLICE:"SLICE",
	BuiltinOperatorSIN:"SIN",
	BuiltinOperatorTRANSPOSE_CONV:"TRANSPOSE_CONV",
	BuiltinOperatorSPARSE_TO_DENSE:"SPARSE_TO_DENSE",
	BuiltinOperatorTILE:"TILE",
	BuiltinOperatorEXPAND_DIMS:"EXPAND_DIMS",
	BuiltinOperatorEQUAL:"EQUAL",
	BuiltinOperatorNOT_EQUAL:"NOT_EQUAL",
	BuiltinOperatorLOG:"LOG",
	BuiltinOperatorSUM:"SUM",
	BuiltinOperatorSQRT:"SQRT",
	BuiltinOperatorRSQRT:"RSQRT",
	BuiltinOperatorSHAPE:"SHAPE",
	BuiltinOperatorPOW:"POW",
	BuiltinOperatorARG_MIN:"ARG_MIN",
	BuiltinOperatorFAKE_QUANT:"FAKE_QUANT",
	BuiltinOperatorREDUCE_PROD:"REDUCE_PROD",
	BuiltinOperatorREDUCE_MAX:"REDUCE_MAX",
	BuiltinOperatorPACK:"PACK",
	BuiltinOperatorLOGICAL_OR:"LOGICAL_OR",
	BuiltinOperatorONE_HOT:"ONE_HOT",
	BuiltinOperatorLOGICAL_AND:"LOGICAL_AND",
	BuiltinOperatorLOGICAL_NOT:"LOGICAL_NOT",
	BuiltinOperatorUNPACK:"UNPACK",
	BuiltinOperatorREDUCE_MIN:"REDUCE_MIN",
	BuiltinOperatorFLOOR_DIV:"FLOOR_DIV",
	BuiltinOperatorREDUCE_ANY:"REDUCE_ANY",
	BuiltinOperatorSQUARE:"SQUARE",
	BuiltinOperatorZEROS_LIKE:"ZEROS_LIKE",
	BuiltinOperatorFILL:"FILL",
	BuiltinOperatorFLOOR_MOD:"FLOOR_MOD",
	BuiltinOperatorRANGE:"RANGE",
	BuiltinOperatorRESIZE_NEAREST_NEIGHBOR:"RESIZE_NEAREST_NEIGHBOR",
	BuiltinOperatorLEAKY_RELU:"LEAKY_RELU",
	BuiltinOperatorSQUARED_DIFFERENCE:"SQUARED_DIFFERENCE",
	BuiltinOperatorMIRROR_PAD:"MIRROR_PAD",
	BuiltinOperatorABS:"ABS",
	BuiltinOperatorSPLIT_V:"SPLIT_V",
	BuiltinOperatorUNIQUE:"UNIQUE",
	BuiltinOperatorCEIL:"CEIL",
	BuiltinOperatorREVERSE_V2:"REVERSE_V2",
	BuiltinOperatorADD_N:"ADD_N",
	BuiltinOperatorGATHER_ND:"GATHER_ND",
	BuiltinOperatorCOS:"COS",
	BuiltinOperatorWHERE:"WHERE",
	BuiltinOperatorRANK:"RANK",
	BuiltinOperatorELU:"ELU",
	BuiltinOperatorREVERSE_SEQUENCE:"REVERSE_SEQUENCE",
	BuiltinOperatorMATRIX_DIAG:"MATRIX_DIAG",
	BuiltinOperatorQUANTIZE:"QUANTIZE",
	BuiltinOperatorMATRIX_SET_DIAG:"MATRIX_SET_DIAG",
	BuiltinOperatorROUND:"ROUND",
	BuiltinOperatorHARD_SWISH:"HARD_SWISH",
	BuiltinOperatorIF:"IF",
	BuiltinOperatorWHILE:"WHILE",
	BuiltinOperatorNON_MAX_SUPPRESSION_V4:"NON_MAX_SUPPRESSION_V4",
	BuiltinOperatorNON_MAX_SUPPRESSION_V5:"NON_MAX_SUPPRESSION_V5",
}

