// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CastOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsCastOptions(buf []byte, offset flatbuffers.UOffsetT) *CastOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CastOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CastOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CastOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CastOptions) InDataType() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CastOptions) MutateInDataType(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *CastOptions) OutDataType() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CastOptions) MutateOutDataType(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func CastOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CastOptionsAddInDataType(builder *flatbuffers.Builder, inDataType int8) {
	builder.PrependInt8Slot(0, inDataType, 0)
}
func CastOptionsAddOutDataType(builder *flatbuffers.Builder, outDataType int8) {
	builder.PrependInt8Slot(1, outDataType, 0)
}
func CastOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
