// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type CombinerType = int8
const (
	CombinerTypeSUM CombinerType = 0
	CombinerTypeMEAN CombinerType = 1
	CombinerTypeSQRTN CombinerType = 2
)

var EnumNamesCombinerType = map[CombinerType]string{
	CombinerTypeSUM:"SUM",
	CombinerTypeMEAN:"MEAN",
	CombinerTypeSQRTN:"SQRTN",
}

