// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type CustomOptionsFormat = int8
const (
	CustomOptionsFormatFLEXBUFFERS CustomOptionsFormat = 0
)

var EnumNamesCustomOptionsFormat = map[CustomOptionsFormat]string{
	CustomOptionsFormatFLEXBUFFERS:"FLEXBUFFERS",
}

