// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type FullyConnectedOptionsWeightsFormat = int8
const (
	FullyConnectedOptionsWeightsFormatDEFAULT FullyConnectedOptionsWeightsFormat = 0
	FullyConnectedOptionsWeightsFormatSHUFFLED4x16INT8 FullyConnectedOptionsWeightsFormat = 1
)

var EnumNamesFullyConnectedOptionsWeightsFormat = map[FullyConnectedOptionsWeightsFormat]string{
	FullyConnectedOptionsWeightsFormatDEFAULT:"DEFAULT",
	FullyConnectedOptionsWeightsFormatSHUFFLED4x16INT8:"SHUFFLED4x16INT8",
}

