// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HardSwishOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsHardSwishOptions(buf []byte, offset flatbuffers.UOffsetT) *HardSwishOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HardSwishOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HardSwishOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HardSwishOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func HardSwishOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HardSwishOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
