// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type LSHProjectionType = int8
const (
	LSHProjectionTypeUNKNOWN LSHProjectionType = 0
	LSHProjectionTypeSPARSE LSHProjectionType = 1
	LSHProjectionTypeDENSE LSHProjectionType = 2
)

var EnumNamesLSHProjectionType = map[LSHProjectionType]string{
	LSHProjectionTypeUNKNOWN:"UNKNOWN",
	LSHProjectionTypeSPARSE:"SPARSE",
	LSHProjectionTypeDENSE:"DENSE",
}

