// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type LSTMKernelType = int8
const (
	LSTMKernelTypeFULL LSTMKernelType = 0
	LSTMKernelTypeBASIC LSTMKernelType = 1
)

var EnumNamesLSTMKernelType = map[LSTMKernelType]string{
	LSTMKernelTypeFULL:"FULL",
	LSTMKernelTypeBASIC:"BASIC",
}

