// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type MirrorPadMode = int8
const (
	MirrorPadModeREFLECT MirrorPadMode = 0
	MirrorPadModeSYMMETRIC MirrorPadMode = 1
)

var EnumNamesMirrorPadMode = map[MirrorPadMode]string{
	MirrorPadModeREFLECT:"REFLECT",
	MirrorPadModeSYMMETRIC:"SYMMETRIC",
}

