// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type Padding = int8
const (
	PaddingSAME Padding = 0
	PaddingVALID Padding = 1
)

var EnumNamesPadding = map[Padding]string{
	PaddingSAME:"SAME",
	PaddingVALID:"VALID",
}

