// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type QuantizationDetails = byte
const (
	QuantizationDetailsNONE QuantizationDetails = 0
	QuantizationDetailsCustomQuantization QuantizationDetails = 1
)

var EnumNamesQuantizationDetails = map[QuantizationDetails]string{
	QuantizationDetailsNONE:"NONE",
	QuantizationDetailsCustomQuantization:"CustomQuantization",
}

