// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReducerOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsReducerOptions(buf []byte, offset flatbuffers.UOffsetT) *ReducerOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReducerOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReducerOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReducerOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReducerOptions) KeepDims() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReducerOptions) MutateKeepDims(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func ReducerOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReducerOptionsAddKeepDims(builder *flatbuffers.Builder, keepDims byte) {
	builder.PrependByteSlot(0, keepDims, 0)
}
func ReducerOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
