// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResizeBilinearOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsResizeBilinearOptions(buf []byte, offset flatbuffers.UOffsetT) *ResizeBilinearOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResizeBilinearOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ResizeBilinearOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResizeBilinearOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResizeBilinearOptions) AlignCorners() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResizeBilinearOptions) MutateAlignCorners(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func ResizeBilinearOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ResizeBilinearOptionsAddAlignCorners(builder *flatbuffers.Builder, alignCorners byte) {
	builder.PrependByteSlot(2, alignCorners, 0)
}
func ResizeBilinearOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
