// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResizeNearestNeighborOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsResizeNearestNeighborOptions(buf []byte, offset flatbuffers.UOffsetT) *ResizeNearestNeighborOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResizeNearestNeighborOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ResizeNearestNeighborOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResizeNearestNeighborOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResizeNearestNeighborOptions) AlignCorners() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResizeNearestNeighborOptions) MutateAlignCorners(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func ResizeNearestNeighborOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ResizeNearestNeighborOptionsAddAlignCorners(builder *flatbuffers.Builder, alignCorners byte) {
	builder.PrependByteSlot(0, alignCorners, 0)
}
func ResizeNearestNeighborOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
