// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SequenceRNNOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSequenceRNNOptions(buf []byte, offset flatbuffers.UOffsetT) *SequenceRNNOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SequenceRNNOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SequenceRNNOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SequenceRNNOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SequenceRNNOptions) TimeMajor() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SequenceRNNOptions) MutateTimeMajor(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *SequenceRNNOptions) FusedActivationFunction() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SequenceRNNOptions) MutateFusedActivationFunction(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func SequenceRNNOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SequenceRNNOptionsAddTimeMajor(builder *flatbuffers.Builder, timeMajor byte) {
	builder.PrependByteSlot(0, timeMajor, 0)
}
func SequenceRNNOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction int8) {
	builder.PrependInt8Slot(1, fusedActivationFunction, 0)
}
func SequenceRNNOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
