// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SparseToDenseOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSparseToDenseOptions(buf []byte, offset flatbuffers.UOffsetT) *SparseToDenseOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SparseToDenseOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SparseToDenseOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SparseToDenseOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SparseToDenseOptions) ValidateIndices() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SparseToDenseOptions) MutateValidateIndices(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func SparseToDenseOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SparseToDenseOptionsAddValidateIndices(builder *flatbuffers.Builder, validateIndices byte) {
	builder.PrependByteSlot(0, validateIndices, 0)
}
func SparseToDenseOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
