// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SubOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSubOptions(buf []byte, offset flatbuffers.UOffsetT) *SubOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SubOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SubOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SubOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SubOptions) FusedActivationFunction() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SubOptions) MutateFusedActivationFunction(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func SubOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SubOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction int8) {
	builder.PrependInt8Slot(0, fusedActivationFunction, 0)
}
func SubOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
