// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SVDFOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsSVDFOptions(buf []byte, offset flatbuffers.UOffsetT) *SVDFOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SVDFOptions{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SVDFOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SVDFOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SVDFOptions) Rank() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SVDFOptions) MutateRank(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *SVDFOptions) FusedActivationFunction() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SVDFOptions) MutateFusedActivationFunction(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func SVDFOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SVDFOptionsAddRank(builder *flatbuffers.Builder, rank int32) {
	builder.PrependInt32Slot(0, rank, 0)
}
func SVDFOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction int8) {
	builder.PrependInt8Slot(1, fusedActivationFunction, 0)
}
func SVDFOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
