// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

type TensorType = int8
const (
	TensorTypeFLOAT32 TensorType = 0
	TensorTypeFLOAT16 TensorType = 1
	TensorTypeINT32 TensorType = 2
	TensorTypeUINT8 TensorType = 3
	TensorTypeINT64 TensorType = 4
	TensorTypeSTRING TensorType = 5
	TensorTypeBOOL TensorType = 6
	TensorTypeINT16 TensorType = 7
	TensorTypeCOMPLEX64 TensorType = 8
	TensorTypeINT8 TensorType = 9
)

var EnumNamesTensorType = map[TensorType]string{
	TensorTypeFLOAT32:"FLOAT32",
	TensorTypeFLOAT16:"FLOAT16",
	TensorTypeINT32:"INT32",
	TensorTypeUINT8:"UINT8",
	TensorTypeINT64:"INT64",
	TensorTypeSTRING:"STRING",
	TensorTypeBOOL:"BOOL",
	TensorTypeINT16:"INT16",
	TensorTypeCOMPLEX64:"COMPLEX64",
	TensorTypeINT8:"INT8",
}

